const ICON = {
  eyes: '/icons/eyes-icon.svg',
  eyes_white: '/icons/eyes-icon_white.svg',
  search: '/icons/search-icon.svg',
  back: '/icons/back-icon.svg',
  back_white: '/icons/back-icon_white.svg',
  search_list: '/icons/search-icon_list.svg',
  search_list_active: '/icons/search-icon_list_active.svg',
  map: '/icons/map-icon.svg',
  map_active: '/icons/map-icon_active.svg',
  home: '/icons/home-icon.svg',
  home_active: '/icons/home-icon_active.svg',
  report: '/icons/report-icon.svg',
  report_active: '/icons/report-icon_active.svg',
  my: '/icons/my-icon.svg',
  my_active: '/icons/my-icon_active.svg',
  cogwheel: '/icons/cogwheel-icon.svg',
  chevron: '/icons/chevron.svg',
  heart_exhibition: '/icons/heart_exhibition.svg',
  heart_popup: '/icons/heart_popup.svg',
  close: '/icons/close.svg',
  checkbox_off: '/icons/checkbox-off.svg',
  checkbox_on: '/icons/checkbox-on.svg',
  naver: '/icons/naver-icon.svg',
  kakao: '/icons/kakao-icon.svg',
  google: '/icons/google-icon.svg',
  calendar: '/icons/calendar.svg',
}

export { ICON }
